### ISSUE TITLE
not working for me....

### ISSUE THREAD

**Issue by CharlesIrvineKC** [aaronjensen/flycheck-dialyxir#1]
I followed your instructions and have dialyxer installed in my project. However, no flychecking seems to happen in my emacs buffers. I can run dialyzer from the command line and I get the expected output. Any ideas?

**Comment by aaronjensen** [comment]
What is your output of `M-x flycheck-verify-setup`?

**Comment by CharlesIrvineKC** [comment]
See below. I don’t know why elixir-dogma is showing up. It’s not referenced (anymore) in my init.el. Do you think dogma might be causing the problem?

++++++++++++++++++++++++++++++++++++=

Syntax checkers for buffer server.ex in elixir-mode:

  elixir-dogma
    - may enable: yes
    - predicate:  nil
    - executable: Found at /usr/local/bin/mix

  elixir-dialyxir
    - may enable: yes
    - predicate:  t
    - executable: Found at /usr/local/bin/mix

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 31snapshot (package: 20170324.340)
Emacs version:    25.1.1
System:           x86_64-apple-darwin13.4.0
Window system:    ns

**Comment by aaronjensen** [comment]
Dogma is built in to flycheck now, so that's probably why it's still around.

flycheck's next checker system is a tricky beast.

Try doing:

```elisp
      (flycheck-add-next-checker 'elixir-dogma 'elixir-dialyxir)
```

**Comment by CharlesIrvineKC** [comment]
Do you mean put that in my init.el file? That’s what I did. It had no effect. What can I type into an *.ex file to try to trigger dialyzer flychecking?


BTW, I’m using alchemist. Don’t know if that matters.

Do you use flycheck-dogma? I would get runtime errors while editing so had to get rid of it.

**Comment by aaronjensen** [comment]
Yeah, `init.el`, as long as it runs after flycheck is loaded.

Alchemist shouldn't matter, i'm using it too. 

You could try `M-x flycheck-compile` then select `elixir-dialyxir` and see what it does.

**Comment by CharlesIrvineKC** [comment]
fly check-compile elixir-dialyzer gives the output below. Not liking the fullpath option…. Looking into this now.

*******************************************************

mix dialyzer --fullpath --no-check
Starting Dialyzer
dialyzer args: [check_plt: false,
 init_plt: '/Users/charlesirvine/src/elixir/radienz/_build/dev/dialyxir_erlang-19.3_elixir-1.4.2_deps-dev.plt',
 files_rec: ['/Users/charlesirvine/src/elixir/radienz/_build/dev/lib/radienz/ebin'],
 warnings: [:fullpath, :unknown]]
:dialyzer.run error: Unknown dialyzer warning option: fullpath

*************************************

Compilation finished at Fri Mar 31 09:05:59

**Comment by aaronjensen** [comment]
Ah, it looks like `--fullpath` is no longer a command line option. Could you try removing that from the package and trying again? You will need to `M-x eval-buffer` in `flycheck-dialyxir.el` after making the change.

**Comment by CharlesIrvineKC** [comment]
Yeah, I was just noticing the same thing. I’ll make that change and let you know. Thanks

**Comment by CharlesIrvineKC** [comment]
Success. See attached. Thanks!!

**Comment by aaronjensen** [comment]
Great! Would you like to submit a pull request with a fix? Thanks!

**Comment by CharlesIrvineKC** [comment]
I will do that, but I’m a novice GitHub user. Might take me an hour or so.

**Comment by aaronjensen** [comment]
No problem, take your time.
